language: python
python: 3.5
matrix:
  include:
    - python: 3.4
      env: TOX_ENV=py34
    - env: TOX_ENV=py35
    - env: TOX_ENV=docs
    - env: TOX_ENV=flake8
install:
  - pip install tox coveralls
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls
notifications:
  irc: "chat.freenode.net#asphalt"
