language: python
python: 3.4
env:
  - TOX_ENV=py34
#  - TOX_ENV=py35
  - TOX_ENV=docs
  - TOX_ENV=flake8
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
notifications:
  irc: "chat.freenode.net#asphalt"
